spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmg_dev
    username: pmg_dev_user
    password: pmouseguru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: pmg_database_create.sql