spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmg_prod
    username: pmg_prod_user
    password: pmouseguru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false